version: '3.2'

services:
  desk:
    build:
      context: .
      dockerfile: desk/Dockerfile
    image: okteto/desk:0.1.3
  golang:
    build:
      context: .
      dockerfile: golang/Dockerfile
    image: okteto/golang:1
  gradle:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    image: okteto/gradle:5.1-jdk11
  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    image: okteto/node:10
  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    image: okteto/python:3
  ruby:
    build:
      context: .
      dockerfile: ruby/Dockerfile
    image: okteto/ruby:2
