version: '3.7'

services:
  bin:
    image: okteto/bin:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: bin/Dockerfile
  desk:
    image: okteto/desk:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: desk/Dockerfile
  golang:
    image: okteto/golang:1
    build:
      context: .
      dockerfile: golang/Dockerfile
  gradle:
    image: okteto/gradle:5.1-jdk11
    build:
      context: .
      dockerfile: gradle/Dockerfile
  node:
    image: okteto/node:10
    build:
      context: .
      dockerfile: node/Dockerfile
  openfaas:
    image: okteto/openfaas:golang
    build:
      context: .
      dockerfile: openfaas/Dockerfile
  python:
    image: okteto/python:3
    build:
      context: .
      dockerfile: python/Dockerfile
  ruby:
    image: okteto/ruby:2
    build:
      context: .
      dockerfile: ruby/Dockerfile
